# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
- release
- deploy

variables:
  CHARTNAME: build-monitor

release:
  stage: release
  only:
  - master
  image: docker.ninjaneers.de/semantic-release:latest
  script:
  - semantic-release
  - git describe --tags --abbrev=0 | cut -c 2- > release-version.txt
  artifacts:
    paths:
    - release-version.txt

build:
  stage: deploy
  only:
  - master
  image: docker.ninjaneers.de/helm-kubectl:1.1.1
  dependencies:
  - release
  script:
  - export TAG=$(cat release-version.txt)
  - mkdir /$CHARTNAME
  - cp -R * /$CHARTNAME
  - cd /$CHARTNAME
  - helm package . --version $TAG
  - helm push . --version=$TAG ninjaneers
